version: "3"

services:
  app:
    container_name: next-app
    image: next-app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - portfolio-network
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - portfolio-network

networks:
  portfolio-network:
