name: Deploy Portfolio App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into Linode and deploy
        run: |

          sshpass -p 'sR689359@' ssh -o StrictHostKeyChecking=no ubuntu@170.187.237.22 'bash -s' << 'EOF'
            cd /home/ubuntu/portfolio
            git checkout main  # Pull latest changes from main branch
            git pull --ff
            docker compose -f docker-compose.yml up --build            # Install dependencies
          EOF
